---
- name: Create exports file
  template: src=exports.j2 dest=/etc/exports owner=root group=root mode=0644
  notify: Restart nfs

- name: Create /vagrant/bin
  file: path=/vagrant/bin state=directory mode=0755

- name: Create mount script
  template: src=mount.j2 dest=/vagrant/bin/mount mode=0755

- name: Create unmount script
  template: src=unmount.j2 dest=/vagrant/bin/unmount mode=0755
