---
- name: Create /opt/photos_web
  file: path=/opt/photos_web state=directory owner=vagrant group=vagrant mode=0755

- name: Clone photos web
  git: repo=git@github.com:samtny/photos-web.git dest=/opt/photos_web accept_hostkey=true
  sudo: no

- name: Create /var/www/photos_web symlink
  file: src=/opt/photos_web dest=/var/www/photos_web state=link owner=vagrant group=www-data

- name: Create photos_web vhost entry
  template: src=photos_web.j2 dest=/etc/nginx/sites-available/photos_web owner=root group=root mode=644
  notify: Reload nginx

- name: Enable photos_web vhost
  file: src=/etc/nginx/sites-available/photos_web dest=/etc/nginx/sites-enabled/photos_web state=link owner=root group=root mode=644
  notify: Reload nginx

- name: Install photos_web gulp
  command: npm install -g gulp chdir=/opt/photos_web creates=/usr/bin/gulp

- name: Install photos_web npm packages
  command: npm install chdir=/opt/photos_web creates=/opt/photos_web/node_modules/gulp/package.json
  become: yes
  become_user: vagrant

- name: Invoke photos_web gulp default task
  command: gulp chdir=/opt/photos_web creates=/opt/photos_web/dist/css/style.css
  become: yes
  become_user: vagrant
